const i18Obj = {
  en: {
    titleName: 'Lingvanex. Test task',
    companyFirstLetter: "L",
    buttonLang: 'EN',
    home: 'HOME',
    about: 'LANGUAGE SOLUTION',
    education: 'PRODUCT',
    heroTitle: 'Travel and Hospitality',
    heroDescription: 'Offline & Online Translation: image translation, translation history, file translation, bookmarks, dictionary meaning.',
    heroButton: 'Request a free trial',
    languageSolutionTitle: 'Our language solution',
    languageSolutionDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
    languageCardTitle1: 'Translation', 
    languageCardDescription1: 'Unlimited and secure translation for fixed price. Translate billions of characters per day',
    languageCardTitle2: 'Social listening', 
    languageCardDescription2: 'Unlimited and secure translation for fixed price. Translate billions of characters per day',
    languageCardTitle3: 'Content generation', 
    languageCardDescription3: 'Unlimited and secure translation for fixed price. Translate billions of characters per day',
    productForTitle: 'Who is this product for?',
    productForDescription: 'Lingvanex Bot can simply solve a language barrier problem in your team, community, with your international clients and outsourcing partners. It automatically identifies the languages in a conversation and translates all messages of your team members into a chosen language.',
    slide1_title: 'For travelers',
    slide1_item1: 'Highlight one word in the text on the page',
    slide1_item2: 'Word meaning, pronunciation, synonyms, hypernyms, hyponyms. And more',
    slide1_item3: 'Highlight one word in the text on the page',
    slide1_item4: 'Word meaning, pronunciation, synonyms, hypernyms, hyponyms. And more',
    slide2_title: 'For travel organization',
    slide2_item1: 'Highlight one word in the text on the page',
    slide2_item2: 'Word meaning, pronunciation, synonyms, hypernyms, hyponyms. And more',
    slide2_item3: 'Highlight one word in the text on the page',
    slide2_item4: 'Word meaning, pronunciation, synonyms, hypernyms, hyponyms. And more',
    slide3_title: 'For employees',
    slide3_item1: 'Highlight one word in the text on the page',
    slide3_item2: 'Word meaning, pronunciation, synonyms, hypernyms, hyponyms. And more',
    slide3_item3: 'Highlight one word in the text on the page',
    slide3_item4: 'Word meaning, pronunciation, synonyms, hypernyms, hyponyms. And more',
  },

  ru: {
    titleName: 'Лингванекс. Тестовое задание',
    companyFirstLetter: "Л",
    buttonLang: 'RU',
    home: 'В НАЧАЛО',
    about: 'ЯЗЫКОВОЕ РЕШЕНИЕ',
    education: 'ПРОДУКТ',
    heroTitle: 'Туризм и гостеприимство',
    heroDescription: 'Офлайн и онлайн перевод: перевод изображений, история переводов, перевод файлов, закладки, словарный перевод.',
    heroButton: 'Бесплатная пробная версия',
    languageSolutionTitle: 'Наше языковое решение',
    languageSolutionDescription: 'Lorem Ipsum - это просто фиктивный текст печати и верстки. Lorem Ipsum является стандартным фиктивным текстом отрасли с момента своего создания.',
    languageCardTitle1: 'Перевод',
    languageCardDescription1: 'Неограниченный и безопасный перевод по фиксированной цене. Переводите миллиарды символов в день',
    languageCardTitle2: 'Социальное прослушивание', 
    languageCardDescription2: 'Неограниченный и безопасный перевод по фиксированной цене. Переводите миллиарды символов в день',
    languageCardTitle3: 'Генерация контента', 
    languageCardDescription3: 'Неограниченный и безопасный перевод по фиксированной цене. Переводите миллиарды символов в день',
    productForTitle: 'Для кого этот продукт?',
    productForDescription: 'Lingvanex Bot может просто решить проблему языкового барьера в вашей команде, сообществе, с вашими международными клиентами и партнерами по аутсорсингу. Он автоматически определяет языки в разговоре и переводит все сообщения членов вашей команды на выбранный язык.',
    slide1_title: 'Для путешественников',
    slide1_item1: 'Выделите одно слово в тексте на странице.',
    slide1_item2: 'Значение слова, произношение, синонимы, гиперонимы, гипонимы. И более.',
    slide1_item3: 'Выделите одно слово в тексте на странице.',
    slide1_item4: 'Значение слова, произношение, синонимы, гиперонимы, гипонимы. И более.',
    slide2_title: 'Для организации путешествий',
    slide2_item1: 'Выделите одно слово в тексте на странице.',
    slide2_item2: 'Значение слова, произношение, синонимы, гиперонимы, гипонимы. И более.',
    slide2_item3: 'Выделите одно слово в тексте на странице.',
    slide2_item4: 'Значение слова, произношение, синонимы, гиперонимы, гипонимы. И более.',
    slide3_title: 'Для сотрудников',
    slide3_item1: 'Выделите одно слово в тексте на странице.',
    slide3_item2: 'Значение слова, произношение, синонимы, гиперонимы, гипонимы. И более.',
    slide3_item3: 'Выделите одно слово в тексте на странице.',
    slide3_item4: 'Значение слова, произношение, синонимы, гиперонимы, гипонимы. И более.',
  },
};
export default i18Obj;
